// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf5Z6T3fQL9d16354ab',
    messagingSenderId: '632817783218',
    projectId: 'recipeapp-90db2',
    storageBucket: 'recipeapp-90db2.firebasestorage.app',
  );

  static const FirebaseOptions maeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf5Z6T3fQL_0OQX0Ar1fD-T7PYcilLzO8',
    appId: '1:632817783218:web:757beefc4c7f526d6354ab',
    messagingSenderId: '632817783218',
    projectId: 'recipeapp-90db2',
    authDomain: 'recipeapp-90db2.firebaseapp.com',
    storageBucket: 'recipeapp-90db2.firebasestorage.app',
    measurementId: 'G-FMNXY12Y32',
  );
}
